### ISSUE TITLE
.opus format and progress feedback in the UI

### ISSUE THREAD

**Issue by mirko77** [playerofgames/replaygain-scan#1]
Hi,

great job!

Any chance of adding .opus support and viewing the progress feedback in the UI (file by file)?

Cheers

**Comment by playerofgames** [comment]
The scan works by executing command line tools which scan and write the replay gain tags. If such a tool exists for opus files, it would be feasible to include them, though I will not have time to do it.

Regarding progress feedback, currently it's folder by folder. I don't think it's worth trying to produce faster feedback than that for the target use case (one-shot folder, or larger hierarchy). It would require closer inspection and manipulation of the output of aforementioned command line scan tools.

Hopefully the tool meets your needs for non-opus files!
